spring:
  rabbitmq:
    listener:
      direct:
        acknowledge-mode: manual
  jpa:
    database: h2
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS SHOP
    name: db
    username: sa
    password: sa


logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      github:
        ekgreen: DEBUG