auth:
  secret: ${AUTH_SERVICE_SECRET}

spring:
  jpa:
    open-in-view: false # не будем напрягать бд
  datasource:
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/db
    username: postgres # понятно что креды не надо так писать
    password: postgres # понятно что креды не надо так писать

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      github:
        ekgreen: DEBUG

